version: 2
updates:
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /blockchain/public-anchor
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /blockchain/fabric/chaincode
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
