/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CaseIntegrityAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorMerkleRoot"
      | "anchors"
      | "authority"
      | "verifyAnchor"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MerkleRootAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorMerkleRoot",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAnchor",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAnchor",
    data: BytesLike
  ): Result;
}

export namespace MerkleRootAnchoredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    merkleRoot: BytesLike,
    metadataCommitment: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    merkleRoot: string,
    metadataCommitment: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    merkleRoot: string;
    metadataCommitment: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CaseIntegrityAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): CaseIntegrityAnchor;
  waitForDeployment(): Promise<this>;

  interface: CaseIntegrityAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorMerkleRoot: TypedContractMethod<
    [root: BytesLike, batchId: BigNumberish, metadataCommitment: BytesLike],
    [void],
    "nonpayable"
  >;

  anchors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        merkleRoot: string;
        metadataCommitment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  authority: TypedContractMethod<[], [string], "view">;

  verifyAnchor: TypedContractMethod<
    [batchId: BigNumberish, root: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorMerkleRoot"
  ): TypedContractMethod<
    [root: BytesLike, batchId: BigNumberish, metadataCommitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        merkleRoot: string;
        metadataCommitment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAnchor"
  ): TypedContractMethod<
    [batchId: BigNumberish, root: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "MerkleRootAnchored"
  ): TypedContractEvent<
    MerkleRootAnchoredEvent.InputTuple,
    MerkleRootAnchoredEvent.OutputTuple,
    MerkleRootAnchoredEvent.OutputObject
  >;

  filters: {
    "MerkleRootAnchored(uint256,bytes32,bytes32,uint256)": TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;
    MerkleRootAnchored: TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;
  };
}
