"""NyayaGraph frozen baseline

Revision ID: 0001_nyayagraph
Revises: 
Create Date: 2026-09-02 09:36:51.508793
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision: str = '0001_nyayagraph'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('authorization_decision', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('required_document_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('merkle_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('public_tx_hash', sa.String(length=200), nullable=True),
    sa.Column('public_chain_id', sa.String(length=80), nullable=True),
    sa.Column('anchor_status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_batches_batch_number'), 'merkle_batches', ['batch_number'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('fabric_msp_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blockchain_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('chain_type', sa.String(length=60), nullable=False),
    sa.Column('chain_id', sa.String(length=80), nullable=False),
    sa.Column('contract_address', sa.String(length=160), nullable=True),
    sa.Column('transaction_hash', sa.String(length=200), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('anchor_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['merkle_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('merkle_leaves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('leaf_hash', sa.String(length=64), nullable=False),
    sa.Column('leaf_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['merkle_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_leaves_batch_id'), 'merkle_leaves', ['batch_id'], unique=False)
    op.create_index(op.f('ix_merkle_leaves_event_id'), 'merkle_leaves', ['event_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('external_identity_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('clearance_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('demo_password', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('subject_user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_org_id', sa.String(length=36), nullable=True),
    sa.Column('permissions', sa.String(length=120), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_scope', sa.String(length=500), nullable=True),
    sa.Column('is_break_glass', sa.Boolean(), nullable=False),
    sa.Column('supervisor_review_required', sa.Boolean(), nullable=False),
    sa.Column('fabric_tx_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_grants_resource_id'), 'access_grants', ['resource_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('classification_level', sa.Integer(), nullable=False),
    sa.Column('fir_number', sa.String(length=120), nullable=False),
    sa.Column('police_station', sa.String(length=160), nullable=False),
    sa.Column('investigating_officer_id', sa.String(length=36), nullable=True),
    sa.Column('incident_time', sa.DateTime(), nullable=True),
    sa.Column('incident_location', sa.String(length=250), nullable=True),
    sa.Column('next_hearing_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_table('signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('signer_user_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=False),
    sa.Column('public_key_reference', sa.String(length=300), nullable=False),
    sa.Column('signature_value', sa.Text(), nullable=False),
    sa.Column('signed_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_artifact_id'), 'signatures', ['artifact_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_case_id'), 'ai_analyses', ['case_id'], unique=False)
    op.create_table('case_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_role', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_assignments_case_id'), 'case_assignments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_user_id'), 'case_assignments', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=250), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('classification_level', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_code', sa.String(length=80), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classification_level', sa.Integer(), nullable=False),
    sa.Column('capture_time', sa.DateTime(), nullable=True),
    sa.Column('capture_location', sa.String(length=250), nullable=True),
    sa.Column('current_custodian_org_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['current_custodian_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_code'), 'evidence', ['evidence_code'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hash_verified', sa.Boolean(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('version_verified', sa.Boolean(), nullable=False),
    sa.Column('anchor_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_case_id'), 'verification_tokens', ['case_id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=True)
    op.create_table('ai_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('claim_type', sa.String(length=80), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_claims_analysis_id'), 'ai_claims', ['analysis_id'], unique=False)
    op.create_table('case_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('participant_type', sa.String(length=80), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_entity_id'), 'case_participants', ['entity_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('classification_level', sa.Integer(), nullable=False),
    sa.Column('storage_policy', sa.String(length=80), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('evidence_custody_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('from_org_id', sa.String(length=36), nullable=True),
    sa.Column('to_org_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('fabric_tx_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_custody_events_evidence_id'), 'evidence_custody_events', ['evidence_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sha256_original', sa.String(length=64), nullable=False),
    sa.Column('sha256_encrypted', sa.String(length=64), nullable=False),
    sa.Column('previous_version_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_reference', sa.String(length=500), nullable=False),
    sa.Column('wrapped_dek', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version_number')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_sha256_original'), 'document_versions', ['sha256_original'], unique=False)
    op.create_table('case_timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('source_document_version_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['source_document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_timeline_events_case_id'), 'case_timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_timeline_events_event_time'), 'case_timeline_events', ['event_time'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('classification_level', sa.Integer(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_case_id'), 'document_chunks', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_version_id'), 'document_chunks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_hash'), 'document_chunks', ['source_hash'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_version_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_case_id'), 'entity_relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_table('ai_claim_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('document_version_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('quote_start', sa.Integer(), nullable=True),
    sa.Column('quote_end', sa.Integer(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['ai_claims.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_claim_sources_claim_id'), 'ai_claim_sources', ['claim_id'], unique=False)
    op.create_index(op.f('ix_ai_claim_sources_document_version_id'), 'ai_claim_sources', ['document_version_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_claim_sources_document_version_id'), table_name='ai_claim_sources')
    op.drop_index(op.f('ix_ai_claim_sources_claim_id'), table_name='ai_claim_sources')
    op.drop_table('ai_claim_sources')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_case_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_document_chunks_source_hash'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_version_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_case_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_case_timeline_events_event_time'), table_name='case_timeline_events')
    op.drop_index(op.f('ix_case_timeline_events_case_id'), table_name='case_timeline_events')
    op.drop_table('case_timeline_events')
    op.drop_index(op.f('ix_document_versions_sha256_original'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_evidence_custody_events_evidence_id'), table_name='evidence_custody_events')
    op.drop_table('evidence_custody_events')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_case_participants_entity_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_table('case_participants')
    op.drop_index(op.f('ix_ai_claims_analysis_id'), table_name='ai_claims')
    op.drop_table('ai_claims')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_case_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_evidence_evidence_code'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_case_assignments_user_id'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_case_id'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index(op.f('ix_ai_analyses_case_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_signatures_artifact_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_access_grants_resource_id'), table_name='access_grants')
    op.drop_table('access_grants')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_merkle_leaves_event_id'), table_name='merkle_leaves')
    op.drop_index(op.f('ix_merkle_leaves_batch_id'), table_name='merkle_leaves')
    op.drop_table('merkle_leaves')
    op.drop_table('blockchain_anchors')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_merkle_batches_batch_number'), table_name='merkle_batches')
    op.drop_table('merkle_batches')
    op.drop_table('compliance_requirements')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
